### PR TITLE
removed doctype from template

### LINKED ISSUE #32: markdown2AmpHTML emits <!doctype html>
great project.
<!doctype html> is a head tag.

Bug:
var markdownString = '# Hello World!' // or read from a .md file
ampl.markdown2AmpHTML({markdown:markdownString}, function(ampHtml) {
  console.log(ampHtml)
})
emits
<!doctype html><h1 >Hello World!</h1>

<!doctype html> should not be emitted in the body. parseHtml() appears to put it no matter what to start. This bug also works if you use parse w/ headOverride: '' //empty header.

### PR DESCRIPTION
**Pull request by pankajpatel**
Fixes #32

### CODE REVIEW

**Comment by Charlotteis** [comment]
Hope it's okay that I merge this @nelsonic, but I guess you gave me the ability for a reason!

**Comment by Charlotteis** [comment]
You might consider PR'ing a version update in the package.json too (I consider this to just need a minor version change). How does the module get published?

**Comment by nelsonic** [comment]
@Charlotteis that is _indeed_ why you have the "power"; _because_ you ~~can be~~ are _trusted_. ❤️  ✅  🚀

**Comment by pankajpatel** [comment]
@nelsonic how would package version move forward?

**Comment by nelsonic** [comment]
@pankajpatel `ampl@1.0.6` on NPM has the changes you have made. thanks again! 🎉

**Comment by iaincollins** [comment]
Hi, version 1.0.6 on NPM still has the bug from #32.

The <!doctype html> is still emitted in the body (and is missing from start of the page, which is flagged as invalid by the validator at https://validator.ampproject.org/).

**Pull request merged**
